version: '3'

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    working_dir: /workspaces
    volumes:
        - ..:/workspaces:cached
    command: /bin/sh -c "while sleep 1000; do :; done"  
    networks:
      - my_network
      
  sql-server:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: sql-server-container
    environment:
      SA_PASSWORD: P@ssw0rd
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    networks:
      - my_network
    restart: unless-stopped

networks:
  my_network:
    driver: bridge